# Generated by Django 3.2 on 2021-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='backlog',
        ),
        migrations.AddField(
            model_name='profile',
            name='backlog',
            field=models.ManyToManyField(related_name='backlog', to='gamerater.Game'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completed',
        ),
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.ManyToManyField(related_name='completed', to='gamerater.Game'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='in_progress',
        ),
        migrations.AddField(
            model_name='profile',
            name='in_progress',
            field=models.ManyToManyField(related_name='in_progress', to='gamerater.Game'),
        ),
        migrations.DeleteModel(
            name='GameList',
        ),
    ]
