# Generated by Django 3.2 on 2021-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerater', '0002_auto_20210608_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='aggregated_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
