# Generated by Django 3.2 on 2021-06-09 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerater', '0003_auto_20210609_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_backlog', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('is_playing', models.BooleanField()),
                ('journal_entry', models.CharField(max_length=10000)),
                ('time_played', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerater.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(through='gamerater.GameRelationship', to='gamerater.Game'),
        ),
    ]
