# Generated by Django 3.2 on 2021-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerater', '0004_auto_20210609_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerelationship',
            name='is_backlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamerelationship',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamerelationship',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
