# Generated by Django 3.2 on 2021-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerater', '0005_auto_20210609_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerelationship',
            name='journal_entry',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
