# Generated by Django 3.2 on 2021-08-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerater', '0006_alter_gamerelationship_journal_entry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamerelationship',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_rel'),
        ),
    ]
